# Generated by Django 4.2 on 2025-11-14 15:00

from django.db import migrations
import procurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', procurement.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
